name: CI_pull_request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args:
            build -c ./calendar
        env: 
          TOKEN_ENDPOINT: ${{ secrets.TOKEN_ENDPOINT }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
