name: Deployment

on:
  release:
    types: [published]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      build -c ./calendar
              env:
                  TOKEN_ENDPOINT: ${{ secrets.TOKEN_ENDPOINT }}
                  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
                  APP_ID: ${{ secrets.APP_ID }}
                  APP_SECRET: ${{ secrets.APP_SECRET }}
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
              with:
                  args:
                      push
              env:
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
                  